
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  BucketName:
      Type: String
  DomainsToCheck:
      Type: String

Resources:
  SimpleDeployFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HealthCheckFunction
      Timeout: 300
      Handler: health_check.handler
      Runtime: python3.6
      CodeUri: build/health_check.zip
      Policies: AWSLambdaFullAccess
      Environment:
        Variables:
          DOMAINS: !Ref DomainsToCheck